### ISSUE TITLE
data_utils. preprocess 转义

### ISSUE THREAD

**Issue by iRonaldo** [ssbuild/chatyuan_finetuning#1]
data_utils.py里面的preprocess

为啥要把\n 换成\\n,  \t换成\\t

我看chatyuan 在对话生成式直接在每个角色后面拼上\n就行了
用户：xxx \n 小元：
就可以生成后续文字

preprocess会不会干扰原来的模型了

**Comment by ssbuild** [comment]
> 

\n是特殊字符，分词就UNK了， 你看chatyuan推理过程处理，其实就是preprocess.

**Comment by iRonaldo** [comment]
从randint(1, seqlen) 随机挑了一个位置？然后分左右当input label. 在对话里面这样处理是不是有问题。 他那个 "小元："的prompt就没有意义了

**Comment by ssbuild** [comment]
> 从randint(1, seqlen) 随机挑了一个位置？然后分左右当input label. 在对话里面这样处理是不是有问题。 他那个 "小元："的prompt就没有意义了
滑动窗口训练多伦对话，chatyuan是基于prompt的再训练

**Comment by ssbuild** [comment]
> > 从randint(1, seqlen) 随机挑了一个位置？然后分左右当input label. 在对话里面这样处理是不是有问题。 他那个 "小元："的prompt就没有意义了
> > 滑动窗口训练多伦对话，chatyuan是基于prompt的再训练

**Comment by iRonaldo** [comment]
感觉还是有问题 直接搞 模型可能会遗忘  我qa数据训练了2000步  已经不会写诗 写假条了

**Comment by ssbuild** [comment]
> 感觉还是有问题 直接搞 模型可能会遗忘 我qa数据训练了2000步 已经不会写诗 写假条了

建议咨询下clue chatyuan作者 ，我这个方案应该跟作者不太一致，作者应该没用滑动窗口？ 或者滑动窗口策略跟我不一致。
