### ISSUE TITLE
label生成方式

### ISSUE THREAD

**Issue by iRonaldo** [ssbuild/chatyuan_finetuning#2]
label[:seqlen - s-1] = b_ids[1:seqlen - s]
labels = copy.deepcopy(o2['input_ids'][1:])

label向右一位没有问题，但是我看preprocess时decoder_input前面没有加个bos或者”：“
那其实target第一个字是不是就预测不出来了？

T5源码里面是显示加了decoder_start_token_id 的
            shifted_input_ids = input_ids.new_zeros(input_ids.shape)
            shifted_input_ids[..., 1:] = input_ids[..., :-1].clone()
            shifted_input_ids[..., 0] = decoder_start_token_id

**Comment by ssbuild** [comment]
> label[:seqlen - s-1] = b_ids[1:seqlen - s] labels = copy.deepcopy(o2['input_ids'][1:])
> 
> label向右一位没有问题，但是我看preprocess时decoder_input前面没有加个bos或者”：“ 那其实target第一个字是不是就预测不出来了？
> 
> T5源码里面是显示加了decoder_start_token_id 的 shifted_input_ids = input_ids.new_zeros(input_ids.shape) shifted_input_ids[..., 1:] = input_ids[..., :-1].clone() shifted_input_ids[..., 0] = decoder_start_token_id

you are right , 已更正。
